### ISSUE TITLE
Wrong sintaxis on System file directory in kill.py

### ISSUE THREAD

**Issue by Holcan123** [alt09/experimentsWithPy#2]
c:window/ is an incomplete directory that cause the program to never delete a vulnerable directory    ⸂⸂⸜(രᴗര๑)⸝⸃⸃

**Comment by Holcan123** [comment]
> c:window/ is an incomplete directory that cause the program to never delete a vulnerable directory ⸂⸂⸜(രᴗര๑)⸝⸃⸃

BTW what the hell with the comment (ノಠ益ಠ)ノ彡┻━┻

**Comment by alt09** [comment]
> c:window/ is an incomplete directory that cause the program to never delete a vulnerable directory    ⸂⸂⸜(രᴗര๑)⸝⸃⸃
> 
> 

I don't want to delete any directory that's why it says window instead of windows and is c instead of C also it should be in "" instead of ' '(I'm not sure if it is still working if you change it or not )

**Comment by Holcan123** [comment]
You should try testing it

**Comment by Holcan123** [comment]
did you test it?
